# Form implementation generated from reading ui file 'arches_lintels\ui\ui_active_project_widget.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ActiveProjectWidget(object):
    def setupUi(self, ActiveProjectWidget):
        ActiveProjectWidget.setObjectName("ActiveProjectWidget")
        ActiveProjectWidget.resize(638, 121)
        self.verticalLayout = QtWidgets.QVBoxLayout(ActiveProjectWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.activeProjectWidget = QtWidgets.QWidget(parent=ActiveProjectWidget)
        self.activeProjectWidget.setObjectName("activeProjectWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.activeProjectWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.projectNameLabel = QtWidgets.QLabel(parent=self.activeProjectWidget)
        self.projectNameLabel.setObjectName("projectNameLabel")
        self.verticalLayout_2.addWidget(self.projectNameLabel)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.projectRunButton_2 = QtWidgets.QPushButton(parent=self.activeProjectWidget)
        self.projectRunButton_2.setObjectName("projectRunButton_2")
        self.horizontalLayout_8.addWidget(self.projectRunButton_2)
        self.projectConfigureButton_2 = QtWidgets.QPushButton(parent=self.activeProjectWidget)
        self.projectConfigureButton_2.setObjectName("projectConfigureButton_2")
        self.horizontalLayout_8.addWidget(self.projectConfigureButton_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.messageLabel = QtWidgets.QLabel(parent=self.activeProjectWidget)
        self.messageLabel.setObjectName("messageLabel")
        self.verticalLayout_2.addWidget(self.messageLabel)
        self.progressBar = QtWidgets.QProgressBar(parent=self.activeProjectWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.verticalLayout.addWidget(self.activeProjectWidget)

        self.retranslateUi(ActiveProjectWidget)
        QtCore.QMetaObject.connectSlotsByName(ActiveProjectWidget)

    def retranslateUi(self, ActiveProjectWidget):
        _translate = QtCore.QCoreApplication.translate
        ActiveProjectWidget.setWindowTitle(_translate("ActiveProjectWidget", "Form"))
        self.projectNameLabel.setText(_translate("ActiveProjectWidget", "<project name>"))
        self.projectRunButton_2.setText(_translate("ActiveProjectWidget", "Run"))
        self.projectConfigureButton_2.setText(_translate("ActiveProjectWidget", "Configure"))
        self.messageLabel.setText(_translate("ActiveProjectWidget", "Message"))
