# Form implementation generated from reading ui file 'arches_lintels\ui\ui_active_project_widget.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ActiveProjectWidget(object):
    def setupUi(self, ActiveProjectWidget):
        ActiveProjectWidget.setObjectName("ActiveProjectWidget")
        ActiveProjectWidget.resize(638, 121)
        self.verticalLayout = QtWidgets.QVBoxLayout(ActiveProjectWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.activeProjectWidget = QtWidgets.QWidget(parent=ActiveProjectWidget)
        self.activeProjectWidget.setObjectName("activeProjectWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.activeProjectWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.projectNameLabel = QtWidgets.QLabel(parent=self.activeProjectWidget)
        self.projectNameLabel.setObjectName("projectNameLabel")
        self.verticalLayout_2.addWidget(self.projectNameLabel)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.projectRunButton = QtWidgets.QPushButton(parent=self.activeProjectWidget)
        self.projectRunButton.setObjectName("projectRunButton")
        self.horizontalLayout_8.addWidget(self.projectRunButton)
        self.projectConfigureButton = QtWidgets.QPushButton(parent=self.activeProjectWidget)
        self.projectConfigureButton.setObjectName("projectConfigureButton")
        self.horizontalLayout_8.addWidget(self.projectConfigureButton)
        self.projectVenvButton = QtWidgets.QPushButton(parent=self.activeProjectWidget)
        self.projectVenvButton.setObjectName("projectVenvButton")
        self.horizontalLayout_8.addWidget(self.projectVenvButton)
        self.projectInstallArchesButton = QtWidgets.QPushButton(parent=self.activeProjectWidget)
        self.projectInstallArchesButton.setObjectName("projectInstallArchesButton")
        self.horizontalLayout_8.addWidget(self.projectInstallArchesButton)
        self.projectCreateProjectButton = QtWidgets.QPushButton(parent=self.activeProjectWidget)
        self.projectCreateProjectButton.setObjectName("projectCreateProjectButton")
        self.horizontalLayout_8.addWidget(self.projectCreateProjectButton)
        self.projectInitButton = QtWidgets.QPushButton(parent=self.activeProjectWidget)
        self.projectInitButton.setObjectName("projectInitButton")
        self.horizontalLayout_8.addWidget(self.projectInitButton)
        self.projectStopRunningButton = QtWidgets.QPushButton(parent=self.activeProjectWidget)
        self.projectStopRunningButton.setObjectName("projectStopRunningButton")
        self.horizontalLayout_8.addWidget(self.projectStopRunningButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.messageLabel = QtWidgets.QLabel(parent=self.activeProjectWidget)
        self.messageLabel.setObjectName("messageLabel")
        self.verticalLayout_2.addWidget(self.messageLabel)
        self.progressBar = QtWidgets.QProgressBar(parent=self.activeProjectWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.verticalLayout.addWidget(self.activeProjectWidget)

        self.retranslateUi(ActiveProjectWidget)
        QtCore.QMetaObject.connectSlotsByName(ActiveProjectWidget)

    def retranslateUi(self, ActiveProjectWidget):
        _translate = QtCore.QCoreApplication.translate
        ActiveProjectWidget.setWindowTitle(_translate("ActiveProjectWidget", "Form"))
        self.projectNameLabel.setText(_translate("ActiveProjectWidget", "<project name>"))
        self.projectRunButton.setText(_translate("ActiveProjectWidget", "Run"))
        self.projectConfigureButton.setText(_translate("ActiveProjectWidget", "Configure"))
        self.projectVenvButton.setText(_translate("ActiveProjectWidget", "Create virtual environment"))
        self.projectInstallArchesButton.setText(_translate("ActiveProjectWidget", "Install Arches"))
        self.projectCreateProjectButton.setText(_translate("ActiveProjectWidget", "Create Project"))
        self.projectInitButton.setText(_translate("ActiveProjectWidget", "Initialise Project"))
        self.projectStopRunningButton.setText(_translate("ActiveProjectWidget", "Stop"))
        self.messageLabel.setText(_translate("ActiveProjectWidget", "Message"))
