# Form implementation generated from reading ui file 'arches_lintels\ui\ui_create_arches_project.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CreateArchesProject(object):
    def setupUi(self, CreateArchesProject):
        CreateArchesProject.setObjectName("CreateArchesProject")
        CreateArchesProject.resize(300, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(CreateArchesProject)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.createArchesProjectScrollArea = QtWidgets.QScrollArea(parent=CreateArchesProject)
        self.createArchesProjectScrollArea.setWidgetResizable(True)
        self.createArchesProjectScrollArea.setObjectName("createArchesProjectScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 298, 498))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.archesProjectName = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.archesProjectName.setObjectName("archesProjectName")
        self.horizontalLayout.addWidget(self.archesProjectName)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.archesVersions = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.archesVersions.setObjectName("archesVersions")
        self.horizontalLayout_2.addWidget(self.archesVersions)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.archesApps = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.archesApps.setObjectName("archesApps")
        self.horizontalLayout_3.addWidget(self.archesApps)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.pushButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.createProjectButton = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.createProjectButton.setObjectName("createProjectButton")
        self.verticalLayout_2.addWidget(self.createProjectButton)
        self.errorMessageLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.errorMessageLabel.setText("")
        self.errorMessageLabel.setObjectName("errorMessageLabel")
        self.verticalLayout_2.addWidget(self.errorMessageLabel)
        self.createArchesProjectScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.createArchesProjectScrollArea)

        self.retranslateUi(CreateArchesProject)
        QtCore.QMetaObject.connectSlotsByName(CreateArchesProject)

    def retranslateUi(self, CreateArchesProject):
        _translate = QtCore.QCoreApplication.translate
        CreateArchesProject.setWindowTitle(_translate("CreateArchesProject", "Dialog"))
        self.label.setText(_translate("CreateArchesProject", "Name (*)"))
        self.label_2.setText(_translate("CreateArchesProject", "Version (*)"))
        self.label_3.setText(_translate("CreateArchesProject", "Arches Apps"))
        self.label_4.setText(_translate("CreateArchesProject", "Advanced"))
        self.pushButton.setText(_translate("CreateArchesProject", "↓"))
        self.createProjectButton.setText(_translate("CreateArchesProject", "Create"))
